import {
    TYPE_INSTITUTION
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const INSTITUTION_RESULTS_LIST = TYPE_INSTITUTION + RESULTS_LIST
export const INSTITUTION_RESULTS_LIST_REQUEST = INSTITUTION_RESULTS_LIST + "_REQUEST"
export const INSTITUTION_RESULTS_LIST_SUCCESS = INSTITUTION_RESULTS_LIST + "_SUCCESS"
export const INSTITUTION_RESULTS_LIST_ERROR = INSTITUTION_RESULTS_LIST + "_ERROR"
