import {
    TYPE_TITLE
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const TITLE_RESULTS_LIST = TYPE_TITLE + RESULTS_LIST
export const TITLE_RESULTS_LIST_REQUEST = TITLE_RESULTS_LIST + "_REQUEST"
export const TITLE_RESULTS_LIST_SUCCESS = TITLE_RESULTS_LIST + "_SUCCESS"
export const TITLE_RESULTS_LIST_ERROR = TITLE_RESULTS_LIST + "_ERROR"
