import {
    TYPE_INSTRUCTOR
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const INSTRUCTOR_RESULTS_LIST = TYPE_INSTRUCTOR + RESULTS_LIST
export const INSTRUCTOR_RESULTS_LIST_REQUEST = INSTRUCTOR_RESULTS_LIST + "REQUEST"
export const INSTRUCTOR_RESULTS_LIST_SUCCESS = INSTRUCTOR_RESULTS_LIST + "SUCCESS"
export const INSTRUCTOR_RESULTS_LIST_ERROR = INSTRUCTOR_RESULTS_LIST + "ERROR"
