import {
    TYPE_FIELD
} from '../store'

const RESULT = "RESULT"
const FIELD_RESULT = TYPE_FIELD + RESULT
export const FIELD_RESULT_REQUEST = FIELD_RESULT + "REQUEST"
export const FIELD_RESULT_SUCCESS = FIELD_RESULT + "SUCCESS"
