import {
    TYPE_TITLE,
    TYPE_AUTHOR,
    TYPE_INSTITUTION,
    TYPE_FIELD,
    TYPE_COUNTRY,
    TYPE_PUBLISHER
} from '../../store-types'

const MOST_FRECUENT = "MOST_FRECUENT"
export const MOST_FRECUENT_TYPE_UPDATE = "MOST_FRECUENT_TYPE_UPDATE"

export const MOST_FRECUENT_TITLE = MOST_FRECUENT + TYPE_TITLE
export const MOST_FRECUENT_FIELD = MOST_FRECUENT + TYPE_FIELD
export const MOST_FRECUENT_AUTHOR = MOST_FRECUENT + TYPE_AUTHOR
export const MOST_FRECUENT_INSTITUTION = MOST_FRECUENT + TYPE_INSTITUTION
export const MOST_FRECUENT_COUNTRY = MOST_FRECUENT + TYPE_COUNTRY
export const MOST_FRECUENT_PUBLISHER = MOST_FRECUENT + TYPE_PUBLISHER

export const MOST_FRECUENT_TITLE_REQUEST = MOST_FRECUENT_TITLE + "_REQUEST"
export const MOST_FRECUENT_FIELD_REQUEST = MOST_FRECUENT_FIELD + "_REQUEST"
export const MOST_FRECUENT_AUTHOR_REQUEST = MOST_FRECUENT_AUTHOR + "_REQUEST"
export const MOST_FRECUENT_INSTITUTION_REQUEST = MOST_FRECUENT_INSTITUTION + "_REQUEST"
export const MOST_FRECUENT_COUNTRY_REQUEST = MOST_FRECUENT_COUNTRY + "_REQUEST"
export const MOST_FRECUENT_PUBLISHER_REQUEST = MOST_FRECUENT_PUBLISHER + "_REQUEST"

export const MOST_FRECUENT_TITLE_ERROR = MOST_FRECUENT_TITLE + "_ERROR"
export const MOST_FRECUENT_FIELD_ERROR = MOST_FRECUENT_FIELD + "_ERROR"
export const MOST_FRECUENT_AUTHOR_ERROR = MOST_FRECUENT_AUTHOR + "_ERROR"
export const MOST_FRECUENT_INSTITUTION_ERROR = MOST_FRECUENT_INSTITUTION + "_ERROR"
export const MOST_FRECUENT_COUNTRY_ERROR = MOST_FRECUENT_COUNTRY + "_ERROR"
export const MOST_FRECUENT_PUBLISHER_ERROR = MOST_FRECUENT_PUBLISHER + "_ERROR"

export const MOST_FRECUENT_TITLE_SUCCESS = MOST_FRECUENT_TITLE + "_SUCCESS"
export const MOST_FRECUENT_FIELD_SUCCESS = MOST_FRECUENT_FIELD + "_SUCCESS"
export const MOST_FRECUENT_AUTHOR_SUCCESS = MOST_FRECUENT_AUTHOR + "_SUCCESS"
export const MOST_FRECUENT_INSTITUTION_SUCCESS = MOST_FRECUENT_INSTITUTION + "_SUCCESS"
export const MOST_FRECUENT_COUNTRY_SUCCESS = MOST_FRECUENT_COUNTRY + "_SUCCESS"
export const MOST_FRECUENT_PUBLISHER_SUCCESS = MOST_FRECUENT_PUBLISHER + "_SUCCESS"

export const LANDING_REQUEST = "LANDING_REQUEST"
export const LANDING_SUCCESS = "LANDING_SUCCESS"
export const LANDING_ERROR = "LANDING_ERROR"
