import {
    TYPE_TITLE,
    TYPE_AUTHOR,
    TYPE_INSTITUTION,
    TYPE_FIELD,
    TYPE_COUNTRY,
    TYPE_PUBLISHER
} from '../../store-types'

const MOST_FRECUENT = "MOST_FRECUENT"
export const MOST_FRECUENT_TYPE_UPDATE = "MOST_FRECUENT_TYPE_UPDATE"

export const MOST_FRECUENT_TITLE = MOST_FRECUENT + TYPE_TITLE
export const MOST_FRECUENT_FIELD = MOST_FRECUENT + TYPE_FIELD
export const MOST_FRECUENT_AUTHOR = MOST_FRECUENT + TYPE_AUTHOR
export const MOST_FRECUENT_INSTITUTION = MOST_FRECUENT + TYPE_INSTITUTION
export const MOST_FRECUENT_COUNTRY = MOST_FRECUENT + TYPE_COUNTRY
export const MOST_FRECUENT_PUBLISHER = MOST_FRECUENT + TYPE_PUBLISHER

export const MOST_FRECUENT_TITLE_REQUEST = MOST_FRECUENT_TITLE + "REQUEST"
export const MOST_FRECUENT_FIELD_REQUEST = MOST_FRECUENT_FIELD + "REQUEST"
export const MOST_FRECUENT_AUTHOR_REQUEST = MOST_FRECUENT_AUTHOR + "REQUEST"
export const MOST_FRECUENT_INSTITUTION_REQUEST = MOST_FRECUENT_INSTITUTION + "REQUEST"
export const MOST_FRECUENT_COUNTRY_REQUEST = MOST_FRECUENT_COUNTRY + "REQUEST"
export const MOST_FRECUENT_PUBLISHER_REQUEST = MOST_FRECUENT_PUBLISHER + "REQUEST"

export const MOST_FRECUENT_TITLE_ERROR = MOST_FRECUENT_TITLE + "ERROR"
export const MOST_FRECUENT_FIELD_ERROR = MOST_FRECUENT_FIELD + "ERROR"
export const MOST_FRECUENT_AUTHOR_ERROR = MOST_FRECUENT_AUTHOR + "ERROR"
export const MOST_FRECUENT_INSTITUTION_ERROR = MOST_FRECUENT_INSTITUTION + "ERROR"
export const MOST_FRECUENT_COUNTRY_ERROR = MOST_FRECUENT_COUNTRY + "ERROR"
export const MOST_FRECUENT_PUBLISHER_ERROR = MOST_FRECUENT_PUBLISHER + "ERROR"

export const MOST_FRECUENT_TITLE_SUCCESS = MOST_FRECUENT_TITLE + "SUCCESS"
export const MOST_FRECUENT_FIELD_SUCCESS = MOST_FRECUENT_FIELD + "SUCCESS"
export const MOST_FRECUENT_AUTHOR_SUCCESS = MOST_FRECUENT_AUTHOR + "SUCCESS"
export const MOST_FRECUENT_INSTITUTION_SUCCESS = MOST_FRECUENT_INSTITUTION + "SUCCESS"
export const MOST_FRECUENT_COUNTRY_SUCCESS = MOST_FRECUENT_COUNTRY + "SUCCESS"
export const MOST_FRECUENT_PUBLISHER_SUCCESS = MOST_FRECUENT_PUBLISHER + "SUCCESS"

export const LANDING_REQUEST = "LANDING_REQUEST"
export const LANDING_SUCCESS = "LANDING_SUCCESS"
export const LANDING_ERROR = "LANDING_ERROR"
