import {
    TYPE_PUBLISHER
} from '../../store-types'

const RESULT = "RESULT"
const PUBLISHER_RESULT = TYPE_PUBLISHER + RESULT
export const PUBLISHER_RESULT_REQUEST = PUBLISHER_RESULT + "_REQUEST"
export const PUBLISHER_RESULT_SUCCESS = PUBLISHER_RESULT + "_SUCCESS"
export const PUBLISHER_RESULT_ERROR = PUBLISHER_RESULT + "_ERROR"
