import {
    TYPE_INSTITUTION
} from '../store'

const RESULTS_LIST = "RESULTS_LIST"
const INSTITUTION_RESULTS_LIST = TYPE_INSTITUTION + RESULTS_LIST
export const INSTITUTION_RESULTS_LIST_REQUEST = INSTITUTION_RESULTS_LIST + "REQUEST"
export const INSTITUTION_RESULTS_LIST_SUCCESS = INSTITUTION_RESULTS_LIST + "SUCCESS"
