import {
    TYPE_AUTHOR
} from '../../store-types'

const RESULT = "RESULT"
const AUTHOR_RESULT = TYPE_AUTHOR + RESULT
export const AUTHOR_RESULT_REQUEST = AUTHOR_RESULT + "_REQUEST"
export const AUTHOR_RESULT_SUCCESS = AUTHOR_RESULT + "_SUCCESS"
export const AUTHOR_RESULT_ERROR = AUTHOR_RESULT + "_ERROR"
