import {
    TYPE_INSTITUTION
} from '../../store-types'

const RESULT = "RESULT"
const INSTITUTION_RESULT = TYPE_INSTITUTION + RESULT
export const INSTITUTION_RESULT_REQUEST = INSTITUTION_RESULT + "REQUEST"
export const INSTITUTION_RESULT_SUCCESS = INSTITUTION_RESULT + "SUCCESS"
