import {
    TYPE_FULL_TEXT
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const FULL_TEXT_RESULTS_LIST = TYPE_FULL_TEXT + RESULTS_LIST
export const FULL_TEXT_RESULTS_LIST_REQUEST = FULL_TEXT_RESULTS_LIST + "REQUEST"
export const FULL_TEXT_RESULTS_LIST_SUCCESS = FULL_TEXT_RESULTS_LIST + "SUCCESS"
export const FULL_TEXT_RESULTS_LIST_ERROR = FULL_TEXT_RESULTS_LIST + "ERROR"
