import {
    TYPE_TITLE
} from '../store'

const RESULT = "RESULT"
const TITLE_RESULT = TYPE_TITLE + RESULT
export const TITLE_RESULT_REQUEST = TITLE_RESULT + "REQUEST"
export const TITLE_RESULT_SUCCESS = TITLE_RESULT + "SUCCESS"
