import {
    TYPE_PUBLISHER
} from '../store'

const RESULT = "RESULT"
const PUBLISHER_RESULT = TYPE_PUBLISHER + RESULT
export const PUBLISHER_RESULT_REQUEST = PUBLISHER_RESULT + "REQUEST"
export const PUBLISHER_RESULT_SUCCESS = PUBLISHER_RESULT + "SUCCESS"
