import {
    TYPE_PUBLISHER
} from '../../../store/storeTypes.js'

const RESULT = "RESULT"
const PUBLISHER_RESULT = TYPE_PUBLISHER + RESULT
export const PUBLISHER_RESULT_REQUEST = PUBLISHER_RESULT + "REQUEST"
export const PUBLISHER_RESULT_SUCCESS = PUBLISHER_RESULT + "SUCCESS"
export const PUBLISHER_RESULT_ERROR = PUBLISHER_RESULT + "ERROR"
