import {
    TYPE_PUBLISHER
} from '../../../store/storeTypes.js'

const RESULTS_LIST = "RESULTS_LIST"
const PUBLISHER_RESULTS_LIST = TYPE_PUBLISHER + RESULTS_LIST
export const PUBLISHER_RESULTS_LIST_REQUEST = PUBLISHER_RESULTS_LIST + "REQUEST"
export const PUBLISHER_RESULTS_LIST_SUCCESS = PUBLISHER_RESULTS_LIST + "SUCCESS"
