import {
    TYPE_COUNTRY
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const COUNTRY_RESULTS_LIST = TYPE_COUNTRY + RESULTS_LIST
export const COUNTRY_RESULTS_LIST_REQUEST = COUNTRY_RESULTS_LIST + "_REQUEST"
export const COUNTRY_RESULTS_LIST_SUCCESS = COUNTRY_RESULTS_LIST + "_SUCCESS"
export const COUNTRY_RESULTS_LIST_ERROR = COUNTRY_RESULTS_LIST + "_ERROR"
