import {
    TYPE_FIELD
} from '../../store-types'

const RESULT = "RESULT"
const FIELD_RESULT = TYPE_FIELD + RESULT
export const FIELD_RESULT_REQUEST = FIELD_RESULT + "_REQUEST"
export const FIELD_RESULT_SUCCESS = FIELD_RESULT + "_SUCCESS"
export const FIELD_RESULT_ERROR = FIELD_RESULT + "_ERROR"
