import {
    TYPE_INSTITUTION
} from '../../store-types'

const RESULT = "RESULT"
const INSTITUTION_RESULT = TYPE_INSTITUTION + RESULT
export const INSTITUTION_RESULT_REQUEST = INSTITUTION_RESULT + "_REQUEST"
export const INSTITUTION_RESULT_SUCCESS = INSTITUTION_RESULT + "_SUCCESS"
export const INSTITUTION_RESULT_ERROR = INSTITUTION_RESULT + "_ERROR"
