import {
    TYPE_COUNTRY
} from '../../store-types'

const RESULT = "RESULT"
const COUNTRY_RESULT = TYPE_COUNTRY + RESULT
export const COUNTRY_RESULT_REQUEST = COUNTRY_RESULT + "_REQUEST"
export const COUNTRY_RESULT_SUCCESS = COUNTRY_RESULT + "_SUCCESS"
export const COUNTRY_RESULT_ERROR = COUNTRY_RESULT + "_ERROR"
