export const TYPE_TITLE = 'TYPE_TITLE'
export const TYPE_AUTHOR = 'TYPE_AUTHOR'
export const TYPE_INSTITUTION = 'TYPE_INSTITUTION'
export const TYPE_FIELD = 'TYPE_FIELD'
export const TYPE_COUNTRY = 'TYPE_COUNTRY'
export const TYPE_PUBLISHER = 'TYPE_PUBLISHER'
export const TYPE_INSTITUTION_FIELD = TYPE_INSTITUTION + TYPE_FIELD
export const TYPE_COUNTRY_FIELD = TYPE_COUNTRY + TYPE_FIELD
