import {
    TYPE_COUNTRY_FIELD
} from '../../store-types'

const RESULT = "RESULT"
const COUNTRY_FIELD_RESULT = TYPE_COUNTRY_FIELD + RESULT
export const COUNTRY_FIELD_RESULT_REQUEST = COUNTRY_FIELD_RESULT + "_REQUEST"
export const COUNTRY_FIELD_RESULT_SUCCESS = COUNTRY_FIELD_RESULT + "_SUCCESS"
export const COUNTRY_FIELD_RESULT_ERROR = COUNTRY_FIELD_RESULT + "_ERROR"
