import {
    TYPE_FIELD
} from '../../store-types'

const RESULTS_LIST = "RESULTS_LIST"
const FIELD_RESULTS_LIST = TYPE_FIELD + RESULTS_LIST
export const FIELD_RESULTS_LIST_REQUEST = FIELD_RESULTS_LIST + "REQUEST"
export const FIELD_RESULTS_LIST_SUCCESS = FIELD_RESULTS_LIST + "SUCCESS"
export const FIELD_RESULTS_LIST_ERROR = FIELD_RESULTS_LIST + "ERROR"
